# Use the official Node.js image.
FROM node:18

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY backend/package.json backend/package-lock.json ./

# Install the application dependencies.
RUN npm install

# Copy the rest of the application code.
COPY backend/ .

# Expose the port the app runs on.
EXPOSE 8000

# Start the application.
CMD ["npm", "start"]
